Update default AP SSID & passphrase
pi-top/Wi-Fi-Access-Point-and-Station-Mode pull request #48
Opened 2022-02-07 20:56 UTC by jcapona

| Status  | Ticket/Issue |
| :---: | :--: |
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1182) |

#### Main changes

Updated default access point credentials:
- Hostname is a mix of the hostname and the last 4 characters of the device serial number. eg: `pi-top-1987`
- Passphrase is a random 8 digit number which is set the first time the access point starts.

#### Screenshots (feature, test output, profiling, dev tools etc)

N/A

#### Other notes (e.g. implementation quirks, edge cases, questions / issues)

N/A

#### Manual testing tips

N/A

#### Tag anyone who definitely needs to review or help

N/A

2022-02-08 15:54 UTC, angusjfw commented on wifi-ap-sta
> +	SSID="${SSID:-12345678}"
this default should be realistic eg 4 chars

2022-02-08 16:11 UTC, angusjfw commented
I installed this and rebooted to do onboarding and it worked as expected with new ssid & password.

The only thing that seems a bit off is that after onboarding I checked the config and `/etc/default/wifi-ap-sta` showed the new password but `/etc/hostapd/hostapd.conf` showed the old default still. I turned the AP back on from the miniscreen settings and after that hostapd.conf showed the new password, but it surprised me that config file was not updated on the previous boot.

2022-02-08 18:05 UTC, jcapona commented on wifi-ap-sta
> +	SSID="${SSID:-12345678}"
```suggestion
	SSID="${SSID:-1234}"
```

2022-02-08 22:28 UTC, jcapona commented
> I installed this and rebooted to do onboarding and it worked as expected with new ssid & password.
> 
> The only thing that seems a bit off is that after onboarding I checked the config and `/etc/default/wifi-ap-sta` showed the new password but `/etc/hostapd/hostapd.conf` showed the old default still. I turned the AP back on from the miniscreen settings and after that hostapd.conf showed the new password, but it surprised me that config file was not updated on the previous boot.

When the AP configuration is performed on boot (if AP mode is enabled), we run `wifi-ap-sta configure`. If a `hostapd.conf` file existed by this time, it will move the file to `hostapd.conf.orig` in order to restore it later, and then write our configuration in the file.

Also, when AP mode is disabled, we run a cleanup step; it will remove custom configurations and restore overwritten files (check [here](https://github.com/pi-top/Wi-Fi-Access-Point-and-Station-Mode/blob/master/wifi-ap-sta#L241)). 

The file you see after reboot is a file that was restored when disabling AP mode. I think you're right, that file shouldn't be there but we could fix that in a separate PR.

2022-02-08 22:43 UTC, jcapona commented on wifi-ap-sta
> +	PASSPHRASE="$(shuf -i 10000000-99999999 -n 1)"
updated it to use `/dev/urandom` which is definitely better in terms of generating a secure passphrase...

2022-02-09 10:41 UTC, angusjfw requested changes

2022-02-09 10:41 UTC, angusjfw commented on wifi-ap-sta
> +	PASSPHRASE="$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c8)"
this includes letters as well as _ and -
I think sticking with numbers is good for convenience - there's less potential for confusion over similar characters
```suggestion
	PASSPHRASE="$(< /dev/urandom tr -dc 0-9 | head -c8)"
```

2022-02-09 10:42 UTC, angusjfw commented on wifi-ap-sta
> +	PASSPHRASE="$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c8)"
if you feel it's worth including letters for security, at least leave out the punctuation 'A-Za-z0-9'

2022-02-09 12:01 UTC, jcapona commented on wifi-ap-sta
> +	PASSPHRASE="$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c8)"
```suggestion
	PASSPHRASE="$(< /dev/urandom tr -dc a-km-z0-9 | head -c8)"
```

2022-02-09 12:10 UTC, angusjfw approved these changes

2022-02-09 12:12 UTC, merged